# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherReport' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherReport
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ReactiveSwift', '~> 5.0'
  pod 'FMDB'
  pod 'iOSDropDown'
  pod 'Masonry'
  
  target 'WeatherReportTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherReportUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
